version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: joanacarneiro/udagram-reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: joanacarneiro/udagram-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: joanacarneiro/udagram-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: joanacarneiro/udagram-frontend
