version: "3"
services:
  reverseproxy:
      image: joanacarneiro/udagram-reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: joanacarneiro/udagram-restapi-feed
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_REGION: $POSTGRES_REGION
      POSTGRES_PROFILE: $POSTGRES_PROFILE
      POSTGRES_MEDIA_BUCKET: $POSTGRES_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: joanacarneiro/udagram-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_REGION: $POSTGRES_REGION
      POSTGRES_PROFILE: $POSTGRES_PROFILE
      POSTGRES_MEDIA_BUCKET: $POSTGRES_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: joanacarneiro/udagram-frontend
    ports:
      - "8100:80"
